### ISSUE TITLE
Failed on latest Minix X7 mini

### ISSUE THREAD

**Issue by nvaron** [XBMCil/service.subtitles.torec#3]
13:35:05 T:1947149912  NOTICE: ### [__main__] - Downloading subtitles from '/ajax/sub/sdls.asp?code=B7D1C7E490C2D7DC5B84A59EA49F5D646062685B6175A693C3A3A4BAE4C98EAA5FA764686360897A7A865EBFD7D380E4D0BAE8EB92A464A3'
13:35:08 T:1947149912  NOTICE: ### [TorecSubtitlesDownloader] - Saving to /mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/userdata/addon_data/service.subtitles.torec/temp/Torec.zip (size 32111)
13:35:08 T:1947149912  NOTICE: ### [TorecSubtitlesDownloader] - Unzip the zip file
13:35:09 T:1947149912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: 	
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: (1, 'Operation not permitted', '/mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/userdata/addon_data/service.subtitles.torec/temp/Into.the.Storm.2014.1080p.BluRay.x264.YIFY.srt')
                                            Traceback (most recent call last):
                                              File "/mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/addons/service.subtitles.torec/service.py", line 182, in <module>
                                                subs = download(params["page_id"],params["subtitle_id"],params["filename"])
                                              File "/mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/addons/service.subtitles.torec/service.py", line 102, in download
                                                downloader.saveData(zip, subtitleData)
                                              File "/mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/addons/service.subtitles.torec/resources/lib/TorecSubtitlesDownloader.py", line 185, in saveData
                                                shutil.copy(tempFileName,srtFile)
                                              File "/home/cbro/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/shutil.py", line 89, in copy
                                              File "/home/cbro/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/shutil.py", line 66, in copymode
                                            OSError: (1, 'Operation not permitted', '/mnt/sdcard/Android/data/hk.minix.xbmc/files/.xbmc/userdata/addon_data/service.subtitles.torec/temp/Into.the.Storm.2014.1080p.BluRay.x264.YIFY.srt')
                                            -->End of Python script error report<--

**Comment by slmosl** [comment]
@nvaron, do you still experience the any problem with the 1.0.4 version?
