### ISSUE TITLE
Cannot download subtitles

### ISSUE THREAD

**Issue by Bartzy** [XBMCil/service.subtitles.torec#34]
Hi,

Thanks for the great plugin.

I cannot download any subtitles (search does work). I'm using the latest version.
The relevant entries in the log file are:
```
13:13:09 T:4448  NOTICE: ### [Torec] - {'mansearch': False, 'episode': '3', 'temp': False, 'title': 'Amarillo', 'season': '2', 'tvshow': 'Better Call Saul', 'rar': False, 'year': '', 'file_original_path': u'D:\\TV Shows\\Better Call Saul\\Season 2\\Better.Call.Saul.S02E03.720p.HDTV.x264-AVS.mkv', '3let_language': ['eng', 'heb']}
13:13:09 T:4448  NOTICE: ### [TorecSubtitlesDownloader] - fetching main url for name Better Call Saul
13:13:11 T:4448  NOTICE: ### [__main__] - search took 2.017000
13:13:11 T:4448  NOTICE: ### [__main__] - Found most relevant option to be : S02E03 720p HDTV x264-AVS
13:13:11 T:4448  NOTICE: ### [__main__] - Overall search took 2.017000
13:13:13 T:9184  NOTICE: Thread LanguageInvoker start, auto delete: false
13:13:13 T:9184  NOTICE: -->Python Interpreter Initialized<--
13:13:14 T:9184  NOTICE: ### [__main__] - Downloading subtitles from ''
13:13:14 T:9184  NOTICE: ### [TorecSubtitlesDownloader] - no download link found
13:13:14 T:9184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'rfind'
                                            Traceback (most recent call last):
                                              File "C:\Users\bartz\AppData\Roaming\Kodi\addons\service.subtitles.torec\service.py", line 229, in <module>
                                                subs = download(params["sub_id"], params["option_id"], params["filename"])
                                              File "C:\Users\bartz\AppData\Roaming\Kodi\addons\service.subtitles.torec\service.py", line 129, in download
                                                (file_name, file_ext) = os.path.splitext(subtitle_name)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\ntpath.py", line 199, in splitext
                                                return genericpath._splitext(p, sep, altsep, extsep)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\genericpath.py", line 91, in _splitext
                                                sepIndex = p.rfind(sep)
                                            AttributeError: 'NoneType' object has no attribute 'rfind'
                                            -->End of Python script error report<--
13:13:14 T:7408   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.torec/?action=download&sub_id=43768&option_id=A6A99EDC8FA9A8B8C597AFC2C2&filename=S02E03 720p HDTV x264-AVS
```

Thanks!

**Comment by Bartzy** [comment]
@slmosl Thanks.

Is the official Kodi repository updated with new releases of this addon or should I install from ZIP?
How does the update process for a repository works?

**Comment by slmosl** [comment]
You can either download the zip and install manually, or wait for the official release via [Official Kodi's Scripts Repository](https://github.com/xbmc/repo-scripts) (happens more or less daily, after PR is integrated to master)

**Comment by Bartzy** [comment]
Thanks!

**Comment by shali3** [comment]
I just tested it on my OPENELEC. Works like a charm! @slmosl Thanks!
